In [1]:
import pandas as pd

file_path = "/Users/lokeshadada/Documents/Project2/ExcelFiles/FullData.xlsx" 
df = pd.read_excel(file_path)
df

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price
0,2018,Tata Tiago XZ PETROL,40.77k km,Petrol,Manual,1st owner,"₹7,136/m",3.65 lakh
1,2016,Volkswagen Ameo COMFORTLINE 1.2L,36.06k km,Petrol,Manual,1st owner,"₹7,312/m",3.74 lakh
2,2018,Datsun Redi Go A,33.87k km,Petrol,Manual,2nd owner,"₹3,617/m",1.85 lakh
3,2014,Hyundai Eon ERA +,79.89k km,CNG,Manual,1st owner,"₹9,179/m",1.95 lakh
4,2021,Tata ALTROZ XM PLUS PETROL,58.89k km,CNG,Manual,1st owner,"₹11,437/m",5.85 lakh
...,...,...,...,...,...,...,...,...
175,2016,Toyota Etios Liva V,43.83k km,Petrol,Manual,2nd owner,"₹6,843/m",3.50 lakh
176,2017,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,49.11k km,Petrol,Manual,2nd owner,"₹7,449/m",3.81 lakh
177,2020,Honda City 1.5L I-VTEC ZX,32.90k km,Petrol,Manual,2nd owner,"₹16,709/m",8.78 lakh
178,2017,Maruti Baleno ZETA PETROL 1.2,50.07k km,Petrol,Manual,1st owner,"₹10,049/m",5.14 lakh
179,2015,Honda City 1.5L I-VTEC V MT,96.21k km,Petrol,Manual,2nd owner,"₹8,787/m",3.95 lakh

In [5]:
df.head()

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price
0,2018,Tata Tiago XZ PETROL,40.77k km,Petrol,Manual,1st owner,"₹7,136/m",3.65 lakh
1,2016,Volkswagen Ameo COMFORTLINE 1.2L,36.06k km,Petrol,Manual,1st owner,"₹7,312/m",3.74 lakh
2,2018,Datsun Redi Go A,33.87k km,Petrol,Manual,2nd owner,"₹3,617/m",1.85 lakh
3,2014,Hyundai Eon ERA +,79.89k km,CNG,Manual,1st owner,"₹9,179/m",1.95 lakh
4,2021,Tata ALTROZ XM PLUS PETROL,58.89k km,CNG,Manual,1st owner,"₹11,437/m",5.85 lakh

In [13]:
df.describe()

       CarModelYear
count    180.000000
mean    2018.561111
std        2.784963
min     2012.000000
25%     2017.000000
50%     2018.000000
75%     2021.000000
max     2024.000000

In [17]:
df.tail()

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price
175,2016,Toyota Etios Liva V,43.83k km,Petrol,Manual,2nd owner,"₹6,843/m",3.50 lakh
176,2017,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,49.11k km,Petrol,Manual,2nd owner,"₹7,449/m",3.81 lakh
177,2020,Honda City 1.5L I-VTEC ZX,32.90k km,Petrol,Manual,2nd owner,"₹16,709/m",8.78 lakh
178,2017,Maruti Baleno ZETA PETROL 1.2,50.07k km,Petrol,Manual,1st owner,"₹10,049/m",5.14 lakh
179,2015,Honda City 1.5L I-VTEC V MT,96.21k km,Petrol,Manual,2nd owner,"₹8,787/m",3.95 lakh

In [19]:
df.shape

(180, 8)

In [21]:
df["Kilometers Travelled"] = (
    df["Kilometers Travelled"]
    .str.replace("k km", "", regex=True)
    .astype(float) * 1000  
)

In [23]:
df

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price
0,2018,Tata Tiago XZ PETROL,40770.0,Petrol,Manual,1st owner,"₹7,136/m",3.65 lakh
1,2016,Volkswagen Ameo COMFORTLINE 1.2L,36060.0,Petrol,Manual,1st owner,"₹7,312/m",3.74 lakh
2,2018,Datsun Redi Go A,33870.0,Petrol,Manual,2nd owner,"₹3,617/m",1.85 lakh
3,2014,Hyundai Eon ERA +,79890.0,CNG,Manual,1st owner,"₹9,179/m",1.95 lakh
4,2021,Tata ALTROZ XM PLUS PETROL,58890.0,CNG,Manual,1st owner,"₹11,437/m",5.85 lakh
...,...,...,...,...,...,...,...,...
175,2016,Toyota Etios Liva V,43830.0,Petrol,Manual,2nd owner,"₹6,843/m",3.50 lakh
176,2017,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,49110.0,Petrol,Manual,2nd owner,"₹7,449/m",3.81 lakh
177,2020,Honda City 1.5L I-VTEC ZX,32900.0,Petrol,Manual,2nd owner,"₹16,709/m",8.78 lakh
178,2017,Maruti Baleno ZETA PETROL 1.2,50070.0,Petrol,Manual,1st owner,"₹10,049/m",5.14 lakh
179,2015,Honda City 1.5L I-VTEC V MT,96210.0,Petrol,Manual,2nd owner,"₹8,787/m",3.95 lakh

In [25]:
df["Ownership"] = df["Ownership"].str.extract("(\\d+)").astype(float)
df

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price
0,2018,Tata Tiago XZ PETROL,40770.0,Petrol,Manual,1.0,"₹7,136/m",3.65 lakh
1,2016,Volkswagen Ameo COMFORTLINE 1.2L,36060.0,Petrol,Manual,1.0,"₹7,312/m",3.74 lakh
2,2018,Datsun Redi Go A,33870.0,Petrol,Manual,2.0,"₹3,617/m",1.85 lakh
3,2014,Hyundai Eon ERA +,79890.0,CNG,Manual,1.0,"₹9,179/m",1.95 lakh
4,2021,Tata ALTROZ XM PLUS PETROL,58890.0,CNG,Manual,1.0,"₹11,437/m",5.85 lakh
...,...,...,...,...,...,...,...,...
175,2016,Toyota Etios Liva V,43830.0,Petrol,Manual,2.0,"₹6,843/m",3.50 lakh
176,2017,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,49110.0,Petrol,Manual,2.0,"₹7,449/m",3.81 lakh
177,2020,Honda City 1.5L I-VTEC ZX,32900.0,Petrol,Manual,2.0,"₹16,709/m",8.78 lakh
178,2017,Maruti Baleno ZETA PETROL 1.2,50070.0,Petrol,Manual,1.0,"₹10,049/m",5.14 lakh
179,2015,Honda City 1.5L I-VTEC V MT,96210.0,Petrol,Manual,2.0,"₹8,787/m",3.95 lakh

In [27]:
df["EMI"] = (
    df["EMI"]
    .str.replace("₹", "", regex=True)
    .str.replace("/m", "", regex=True)
    .str.replace(",", "", regex=True)
    .astype(float)
)
df

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price
0,2018,Tata Tiago XZ PETROL,40770.0,Petrol,Manual,1.0,7136.0,3.65 lakh
1,2016,Volkswagen Ameo COMFORTLINE 1.2L,36060.0,Petrol,Manual,1.0,7312.0,3.74 lakh
2,2018,Datsun Redi Go A,33870.0,Petrol,Manual,2.0,3617.0,1.85 lakh
3,2014,Hyundai Eon ERA +,79890.0,CNG,Manual,1.0,9179.0,1.95 lakh
4,2021,Tata ALTROZ XM PLUS PETROL,58890.0,CNG,Manual,1.0,11437.0,5.85 lakh
...,...,...,...,...,...,...,...,...
175,2016,Toyota Etios Liva V,43830.0,Petrol,Manual,2.0,6843.0,3.50 lakh
176,2017,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,49110.0,Petrol,Manual,2.0,7449.0,3.81 lakh
177,2020,Honda City 1.5L I-VTEC ZX,32900.0,Petrol,Manual,2.0,16709.0,8.78 lakh
178,2017,Maruti Baleno ZETA PETROL 1.2,50070.0,Petrol,Manual,1.0,10049.0,5.14 lakh
179,2015,Honda City 1.5L I-VTEC V MT,96210.0,Petrol,Manual,2.0,8787.0,3.95 lakh

In [29]:
df["Price"] = (
    df["Price"]
    .str.replace(" lakh", "", regex=True)
    .astype(float) * 100000  
)
df

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price
0,2018,Tata Tiago XZ PETROL,40770.0,Petrol,Manual,1.0,7136.0,365000.0
1,2016,Volkswagen Ameo COMFORTLINE 1.2L,36060.0,Petrol,Manual,1.0,7312.0,374000.0
2,2018,Datsun Redi Go A,33870.0,Petrol,Manual,2.0,3617.0,185000.0
3,2014,Hyundai Eon ERA +,79890.0,CNG,Manual,1.0,9179.0,195000.0
4,2021,Tata ALTROZ XM PLUS PETROL,58890.0,CNG,Manual,1.0,11437.0,585000.0
...,...,...,...,...,...,...,...,...
175,2016,Toyota Etios Liva V,43830.0,Petrol,Manual,2.0,6843.0,350000.0
176,2017,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,49110.0,Petrol,Manual,2.0,7449.0,381000.0
177,2020,Honda City 1.5L I-VTEC ZX,32900.0,Petrol,Manual,2.0,16709.0,878000.0
178,2017,Maruti Baleno ZETA PETROL 1.2,50070.0,Petrol,Manual,1.0,10049.0,514000.0
179,2015,Honda City 1.5L I-VTEC V MT,96210.0,Petrol,Manual,2.0,8787.0,395000.0

In [31]:
df = df.drop_duplicates()
df

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price
0,2018,Tata Tiago XZ PETROL,40770.0,Petrol,Manual,1.0,7136.0,365000.0
1,2016,Volkswagen Ameo COMFORTLINE 1.2L,36060.0,Petrol,Manual,1.0,7312.0,374000.0
2,2018,Datsun Redi Go A,33870.0,Petrol,Manual,2.0,3617.0,185000.0
3,2014,Hyundai Eon ERA +,79890.0,CNG,Manual,1.0,9179.0,195000.0
4,2021,Tata ALTROZ XM PLUS PETROL,58890.0,CNG,Manual,1.0,11437.0,585000.0
...,...,...,...,...,...,...,...,...
175,2016,Toyota Etios Liva V,43830.0,Petrol,Manual,2.0,6843.0,350000.0
176,2017,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,49110.0,Petrol,Manual,2.0,7449.0,381000.0
177,2020,Honda City 1.5L I-VTEC ZX,32900.0,Petrol,Manual,2.0,16709.0,878000.0
178,2017,Maruti Baleno ZETA PETROL 1.2,50070.0,Petrol,Manual,1.0,10049.0,514000.0
179,2015,Honda City 1.5L I-VTEC V MT,96210.0,Petrol,Manual,2.0,8787.0,395000.0

In [37]:
df.loc[:, "Company Name"] = df["Car Name"].str.split().str[0]
df

,CarModelYear,Car Name,Kilometers Travelled,Fuel Type,Transmission,Ownership,EMI,Price,Company Name
0,2018,Tata Tiago XZ PETROL,40770.0,Petrol,Manual,1.0,7136.0,365000.0,Tata
1,2016,Volkswagen Ameo COMFORTLINE 1.2L,36060.0,Petrol,Manual,1.0,7312.0,374000.0,Volkswagen
2,2018,Datsun Redi Go A,33870.0,Petrol,Manual,2.0,3617.0,185000.0,Datsun
3,2014,Hyundai Eon ERA +,79890.0,CNG,Manual,1.0,9179.0,195000.0,Hyundai
4,2021,Tata ALTROZ XM PLUS PETROL,58890.0,CNG,Manual,1.0,11437.0,585000.0,Tata
...,...,...,...,...,...,...,...,...,...
175,2016,Toyota Etios Liva V,43830.0,Petrol,Manual,2.0,6843.0,350000.0,Toyota
176,2017,Hyundai Grand i10 SPORTZ 1.2 KAPPA VTVT,49110.0,Petrol,Manual,2.0,7449.0,381000.0,Hyundai
177,2020,Honda City 1.5L I-VTEC ZX,32900.0,Petrol,Manual,2.0,16709.0,878000.0,Honda
178,2017,Maruti Baleno ZETA PETROL 1.2,50070.0,Petrol,Manual,1.0,10049.0,514000.0,Maruti
179,2015,Honda City 1.5L I-VTEC V MT,96210.0,Petrol,Manual,2.0,8787.0,395000.0,Honda

In [39]:
df["Company Name"]

0            Tata
1      Volkswagen
2          Datsun
3         Hyundai
4            Tata
          ...
175        Toyota
176       Hyundai
177         Honda
178        Maruti
179         Honda
Name: Company Name, Length: 176, dtype: object

In [41]:
df.to_excel("/Users/lokeshadada/Documents/Project2/ExcelFiles/CleanedData.xlsx", index=False)

print("Data cleaning completed and saved as 'CleanedData.xlsx'")

Data cleaning completed and saved as 'CleanedData.xlsx'